//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteGuard.Protections.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByteGuard.Protections.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================================================================
        ///			MARKETPLACE README
        ///=================================================================
        ///
        ///Please do not open, modify, delete or move any files within this
        ///folder. Doing so could cause a file corruption which can cause
        ///issues with marketplace distribution.
        ///
        ///If your program is marketplace registered and you believe these
        ///files may be corrupt, please view the &apos;Update&apos; tab while you are
        ///in the program management options, this will allow  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string marketplace_readme {
            get {
                return ResourceManager.GetString("marketplace_readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================================================================
        ///		SELF-DISTRIBUTION (BYTEGUARD) README
        ///=================================================================
        ///
        ///This folder contains your protected application and any files that
        ///were located within your specified application directory.
        ///
        ///In this folder you should see a file named &quot;ByteGuard_Protected.exe&quot;,
        ///this is your original application after obfuscation. Any attempts
        ///to open this file before a successful log-in will fail. Please do
        ///no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selfdist_byteguard_readme {
            get {
                return ResourceManager.GetString("selfdist_byteguard_readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================================================================
        ///		SELF-DISTRIBUTION (BYTEGUARD) README
        ///=================================================================
        ///
        ///This folder contains your protected application and any files that
        ///were located within your specified application directory.
        ///
        ///In this folder you should see a file named &quot;ByteGuard_Protected.exe&quot;,
        ///this is your original application after obfuscation. Any attempts
        ///to open this file before a successful log-in will fail. Please do
        ///no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selfdist_custom_readme {
            get {
                return ResourceManager.GetString("selfdist_custom_readme", resourceCulture);
            }
        }
    }
}
